[package]
name = "thereplacebook"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "thereplacebook"
path = "src/main.rs"

[dependencies]
axum = "0.7"
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sqlx = { version = "0.7", features = ["postgres", "runtime-tokio-rustls"] }
dotenvy = "0.15"
tower-http = { version = "0.5", features = ["cors", "fs"] }
hyper = { version = "0.14", features = ["server", "http1", "http2"] }
tokio-stream = { version = "0.1", features = ["net"] }
aws-config = { version = "1.5", features = ["rustls"] }
aws-sdk-secretsmanager = { version = "1.64", features = ["rustls"] }
aws-smithy-types = "1.2.13"
tower = "0.5.2"

# Use rustls instead
rustls = "0.21"
rustls-native-certs = "0.6"