INSERT INTO users (name, image_url, net_worth) VALUES
    ('Elon Musk', 'https://commons.wikimedia.org/wiki/File:Elon_Musk_2015.jpg', '$359.5 billion'),
    ('Mark Zuckerberg', 'https://commons.wikimedia.org/wiki/File:Mark_Zuckerberg_F8_2019_Keynote_(32830578717)_(cropped).jpg', '$236 billion'),
    ('Jeff Bezos', 'https://commons.wikimedia.org/wiki/File:Jeff_Bezos_at_Amazon_Spheres_Grand_Opening_in_Seattle_-_2018_(39074799225).jpg', '$232 billion'),
    ('Larry Ellison', 'https://commons.wikimedia.org/wiki/File:Larry_Ellison_on_stage.jpg', '$192 billion'),
    ('Bernard Arnault', 'https://commons.wikimedia.org/wiki/File:Bernard_Arnault_(3).jpg', '$177 billion'),
    ('Warren Buffett', 'https://commons.wikimedia.org/wiki/File:Warren_Buffett_KU_Visit.jpg', '$133 billion'),
    ('Larry Page', 'https://commons.wikimedia.org/wiki/File:Larry_Page_in_the_EU_Parliament,_June_17,_2009.jpg', '$114 billion'),
    ('Sergey Brin', 'https://commons.wikimedia.org/wiki/File:Sergey_Brin_cropped.jpg', '$112 billion'),
    ('Steve Ballmer', 'https://commons.wikimedia.org/wiki/File:Steve_Ballmer_at_CES_2010_cropped.jpg', '$109 billion'),
    ('Francoise Bettencourt Meyers', 'https://commons.wikimedia.org/wiki/File:Fran%C3%A7oise_Bettencourt_Meyers.jpg', '$95 billion'),
    ('Mukesh Ambani', 'https://commons.wikimedia.org/wiki/File:Mukesh_Ambani.jpg', '$93 billion'),
    ('Carlos Slim Helu', 'https://commons.wikimedia.org/wiki/File:Carlos_Slim_Hel%C3%BA.jpg', '$90 billion'),
    ('Michael Bloomberg', 'https://commons.wikimedia.org/wiki/File:Mike_Bloomberg_2019.jpg', '$82 billion'),
    ('Amancio Ortega', 'https://commons.wikimedia.org/wiki/File:Amancio_Ortega_Gaona.jpg', '$81 billion'),
    ('Zhong Shanshan', 'https://commons.wikimedia.org/wiki/File:Zhong_Shanshan.jpg', '$78 billion'),
    ('Julia Koch & family', 'https://commons.wikimedia.org/wiki/File:Julia_Koch.jpg', '$75 billion'),
    ('Charles Koch', 'https://commons.wikimedia.org/wiki/File:Charles_Koch.jpg', '$75 billion'),
    ('Jim Walton', 'https://commons.wikimedia.org/wiki/File:Jim_Walton.jpg', '$70 billion'),
    ('Rob Walton', 'https://commons.wikimedia.org/wiki/File:Rob_Walton.jpg', '$69 billion'),
    ('Alice Walton', 'https://commons.wikimedia.org/wiki/File:Alice_Walton.jpg', '$68 billion'),
    ('Gautam Adani', 'https://commons.wikimedia.org/wiki/File:Gautam_Adani.jpg', '$67 billion'),
    ('Phil Knight & family', 'https://commons.wikimedia.org/wiki/File:Phil_Knight.jpg', '$65 billion'),
    ('Ma Huateng', 'https://commons.wikimedia.org/wiki/File:Ma_Huateng.jpg', '$64 billion'),
    ('MacKenzie Scott', 'https://commons.wikimedia.org/wiki/File:MacKenzie_Scott.jpg', '$62 billion'),
    ('David Thomson & family', 'https://commons.wikimedia.org/wiki/File:David_Thomson.jpg', '$61 billion'),
    ('Michael Dell', 'https://commons.wikimedia.org/wiki/File:Michael_Dell.jpg', '$60 billion'),
    ('Francois Pinault & family', 'https://commons.wikimedia.org/wiki/File:Fran%C3%A7ois_Pinault.jpg', '$59 billion'),
    ('Jack Ma', 'https://commons.wikimedia.org/wiki/File:Jack_Ma_2015.jpg', '$58 billion'),
    ('Colin Zheng Huang', 'https://commons.wikimedia.org/wiki/File:Colin_Zheng_Huang.jpg', '$57 billion'),
    ('Dieter Schwarz', 'https://commons.wikimedia.org/wiki/File:Dieter_Schwarz.jpg', '$56 billion'),
    ('Sheldon Adelson', 'https://commons.wikimedia.org/wiki/File:Sheldon_Adelson_21_June_2010.jpg', '$55 billion'),
    ('Ken Griffin', 'https://commons.wikimedia.org/wiki/File:Ken_Griffin.jpg', '$54 billion'),
    ('Gina Rinehart', 'https://commons.wikimedia.org/wiki/File:Gina_Rinehart.jpg', '$53 billion'),
    ('Vladimir Potanin', 'https://commons.wikimedia.org/wiki/File:Vladimir_Potanin.jpg', '$52 billion'),
    ('Tadashi Yanai & family', 'https://commons.wikimedia.org/wiki/File:Tadashi_Yanai.jpg', '$51 billion'),
    ('Masayoshi Son', 'https://commons.wikimedia.org/wiki/File:Masayoshi_Son.jpg', '$50 billion'),
    ('Leonid Mikhelson', 'https://commons.wikimedia.org/wiki/File:Leonid_Mikhelson.jpg', '$49 billion'),
    ('Pony Ma', 'https://commons.wikimedia.org/wiki/File:Pony_Ma.jpg', '$48 billion'),
    ('Alain Wertheimer', 'https://commons.wikimedia.org/wiki/File:Alain_Wertheimer.jpg', '$47 billion'),
    ('Gerard Wertheimer', 'https://commons.wikimedia.org/wiki/File:G%C3%A9rard_Wertheimer.jpg', '$47 billion'),
    ('Giovanni Ferrero', 'https://commons.wikimedia.org/wiki/File:Giovanni_Ferrero.jpg', '$46 billion'),
    ('Susanne Klatten', 'https://commons.wikimedia.org/wiki/File:Susanne_Klatten.jpg', '$45 billion'),
    ('Stefan Quandt', 'https://commons.wikimedia.org/wiki/File:Stefan_Quandt.jpg', '$44 billion'),
    ('Li Ka-shing', 'https://commons.wikimedia.org/wiki/File:Li_Ka-shing.jpg', '$43 billion'),
    ('He Xiangjian', 'https://commons.wikimedia.org/wiki/File:He_Xiangjian.jpg', '$42 billion'),
    ('William Lei Ding', 'https://commons.wikimedia.org/wiki/File:William_Lei_Ding.jpg', '$41 billion'),
    ('Gennady Timchenko', 'https://commons.wikimedia.org/wiki/File:Gennady_Timchenko.jpg', '$40 billion')
