INSERT INTO users (name, company, biography, net_worth)
VALUES
                                                            ('Elon Musk', 'Tesla, SpaceX, Neuralink', 'CEO of Tesla and SpaceX, innovator in technology and space travel.', '$359.5 billion'),
                                                            ('Mark Zuckerberg', 'Facebook (Meta)', 'Co-founder and CEO of Facebook (Meta), a leader in social media innovation.', '$236 billion'),
                                                            ('Jeff Bezos', 'Amazon', 'Founder and former CEO of Amazon, revolutionized online retail and e-commerce.', '$232 billion'),
                                                            ('Larry Ellison', 'Oracle', 'Co-founder of Oracle, pioneering enterprise software solutions.', '$192 billion'),
                                                            ('Bernard Arnault', 'LVMH', 'Chairman and CEO of LVMH, leader in luxury goods and fashion.', '$177 billion'),
                                                            ('Warren Buffett', 'Berkshire Hathaway', 'Renowned investor and CEO of Berkshire Hathaway, known for value investing.', '$133 billion'),
                                                            ('Larry Page', 'Google', 'Co-founder of Google, instrumental in developing innovative search algorithms and technology.', '$114 billion'),
                                                            ('Sergey Brin', 'Google', 'Co-founder of Google, driving innovation in technology and digital advertising.', '$112 billion'),
                                                            ('Steve Ballmer', 'Microsoft', 'Former CEO of Microsoft, recognized for his energetic leadership and business acumen.', '$109 billion'),
                                                            ('Mukesh Ambani', 'Reliance Industries', 'Chairman of Reliance Industries, a leader in petrochemicals and telecommunications.', '$93 billion'),
                                                            ('Carlos Slim Helu', 'Grupo Carso', 'Mexican business magnate with diversified investments in telecommunications and finance.', '$90 billion'),
                                                            ('Michael Bloomberg', 'Bloomberg LP', 'Founder of Bloomberg LP, innovator in financial data and media.', '$82 billion'),
                                                            ('Amancio Ortega', 'Inditex', 'Founder of Inditex, revolutionized fashion retail with the Zara brand.', '$81 billion'),
                                                            ('Zhong Shanshan', 'Nongfu Spring', 'Founder of Nongfu Spring, major player in the beverage industry.', '$78 billion'),
                                                            ('Julia Koch & family', 'Koch Industries', 'Family of industrialists influential in energy, manufacturing, and investments.', '$75 billion'),
                                                            ('Charles Koch', 'Koch Industries', 'Executive of Koch Industries, known for his role in American industry and politics.', '$75 billion'),
                                                            ('Jim Walton', 'Walmart', 'Heir to the Walmart fortune, actively involved in retail operations.', '$70 billion'),
                                                            ('Rob Walton', 'Walmart', 'Member of the Walton family, instrumental in the growth of Walmart.', '$69 billion'),
                                                            ('Alice Walton', 'Walmart', 'Part of the Walton family, known for contributions to art and retail innovation.', '$68 billion'),
                                                            ('Gautam Adani', 'Adani Group', 'Indian industrialist and founder of the Adani Group, with interests in energy and infrastructure.', '$67 billion'),
                                                            ('Phil Knight & family', 'Nike', 'Co-founder of Nike, reshaped global sportswear and branding.', '$65 billion'),
                                                            ('Ma Huateng', 'Tencent', 'Founder of Tencent, a leader in digital innovation and internet services.', '$64 billion'),
                                                            ('MacKenzie Scott', 'Amazon', 'Philanthropist and influential figure in charitable giving, formerly married to Jeff Bezos.', '$62 billion'),
                                                            ('David Thomson & family', 'Thomson Reuters', 'Heir to the Thomson fortune, significant in media and publishing.', '$61 billion'),
                                                            ('Michael Dell', 'Dell Technologies', 'Founder of Dell Technologies, a major player in computer technology.', '$60 billion'),
                                                            ('Francois Pinault & family', 'Kering', 'Head of Kering, a global luxury group and significant art collector.', '$59 billion'),
                                                            ('Jack Ma', 'Alibaba Group', 'Co-founder of Alibaba, transformed e-commerce and digital payments in China.', '$58 billion'),
                                                            ('Colin Zheng Huang', 'Pinduoduo', 'Founder of Pinduoduo, innovator in social e-commerce.', '$57 billion'),
                                                            ('Dieter Schwarz', 'Lidl', 'Owner of Lidl, a leader in discount retailing.', '$56 billion'),
                                                            ('Sheldon Adelson', 'Las Vegas Sands', 'Founder of Las Vegas Sands, influential in the casino and hospitality industries.', '$55 billion'),
                                                            ('Ken Griffin', 'Citadel', 'Founder of Citadel, a prominent hedge fund and financial institution.', '$54 billion'),
                                                            ('Gina Rinehart', 'Hancock Prospecting', 'Mining magnate and chair of Hancock Prospecting.', '$53 billion'),
                                                            ('Vladimir Potanin', 'Norilsk Nickel', 'Russian oligarch and major shareholder in Norilsk Nickel.', '$52 billion'),
                                                            ('Tadashi Yanai & family', 'Uniqlo (Fast Retailing)', 'Founder of Uniqlo, revolutionized global retail fashion.', '$51 billion'),
                                                            ('Masayoshi Son', 'SoftBank', 'Founder of SoftBank, known for major investments in technology startups.', '$50 billion'),
                                                            ('Leonid Mikhelson', 'Novatek', 'Russian energy tycoon and chairman of Novatek.', '$49 billion'),
                                                            ('Pony Ma', 'Tencent', 'Founder of Tencent, a key figure in the development of digital services in China.', '$48 billion'),
                                                            ('Alain Wertheimer', 'Chanel', 'Co-owner of Chanel, influential in luxury fashion and cosmetics.', '$47 billion'),
                                                            ('Gerard Wertheimer', 'Chanel', 'Co-owner of Chanel, maintaining the legacy of a premier luxury brand.', '$47 billion'),
                                                            ('Giovanni Ferrero', 'Ferrero Group', 'Executive at Ferrero Group, known for iconic confectionery brands.', '$46 billion'),
                                                            ('Susanne Klatten', 'BMW', 'Heir and influential investor in BMW, a leader in the automotive industry.', '$45 billion'),
                                                            ('Stefan Quandt', 'BMW', 'Major shareholder and influential figure in BMW.', '$44 billion'),
                                                            ('Li Ka-shing', 'CK Hutchison Holdings', 'Hong Kong business magnate with diverse holdings across industries.', '$43 billion'),
                                                            ('He Xiangjian', 'Midea', 'Co-founder of Midea Group, a global leader in home appliances.', '$42 billion'),
                                                            ('William Lei Ding', 'NetEase', 'Founder of NetEase, a major Chinese tech company in online gaming and services.', '$41 billion'),
                                                            ('Gennady Timchenko', 'Volga Group', 'Russian billionaire influential in energy and commodities.', '$40 billion')
    ON CONFLICT (name) DO NOTHING;