name: Deploy to AWS App Runner

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write  # Required for OIDC authentication
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Request OIDC Token for AWS
        id: get-oidc-token
        uses: actions/github-script@v7
        with:
          script: |
            const { data } = await github.rest.actions.getOidcToken();
            console.log(`OIDC Token: ${data.token}`);

      - name: Print OIDC Token (For Debugging)
        run: echo "$OIDC_TOKEN"

      - name: Save OIDC Token to File
        run: echo "$OIDC_TOKEN" > oidc_token.txt
      
      - name: Upload OIDC Token as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: oidc-token
          path: oidc_token.txt
          
