name: Deploy to AWS App Runner

on:
  push:
    branches:
      - main
- name: Get OIDC Token
  run: |
    echo "TOKEN=$(curl -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" -H "Accept: application/json" \
    $ACTIONS_ID_TOKEN_REQUEST_URL | jq -r '.value')" >> $GITHUB_ENV
